;;; workroom-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from workroom.el

(defvar workroom-mode nil "\
Non-nil if Workroom mode is enabled.
See the `workroom-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `workroom-mode'.")
(custom-autoload 'workroom-mode "workroom" nil)
(autoload 'workroom-mode "workroom" "\
Toggle workroom mode.

This is a global minor mode.  If called interactively, toggle the
`Workroom mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='workroom-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'workroom-bookmark-jump-to-room "workroom" "\
Jump to the workroom in bookmark BOOKMARK.

(fn BOOKMARK)")
(autoload 'workroom-bookmark-jump-to-room-set "workroom" "\
Restore the workroom set in bookmark BOOKMARK.

(fn BOOKMARK)")
(register-definition-prefixes "workroom" '("workroom"))

;;; End of scraped data

(provide 'workroom-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; workroom-autoloads.el ends here
