;;; html5-schema-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from html5-schema.el

(when load-file-name (let* ((dir (file-name-directory load-file-name)) (file (expand-file-name "locating-rules.xml" dir))) (eval-after-load 'rng-loc `(progn (add-to-list 'rng-schema-locating-files-default 'file) (add-to-list 'rng-schema-locating-files ,file) (put 'http://whattf.org/datatype-draft 'rng-dt-compile #'nxml-html5-dt-compile)))))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . nxml-mode))
(autoload 'nxml-html5-dt-compile "html5-schema" "\


(fn NAME PARAMS)")
(register-definition-prefixes "html5-schema" '("nxml-html5-dt-"))

;;; End of scraped data

(provide 'html5-schema-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; html5-schema-autoloads.el ends here
